image: Visual Studio 2019

before_build:
  - nuget restore .

build_script:
  - msbuild .\TextTools.sln /p:Configuration=Release

artifacts:
  - path: TextTools\bin\Release\TextTools.vsix

test: off
